name: Docker Image Build and Scan
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Build Docker Image
        run: echo "This represents your build of the Docker image"
 
  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: pull scanner image
        run: |
          docker login registry.aquasec.com -u ${{ secrets.username }} -p ${{ secrets.password}}
          docker pull registry.aquasec.com/scanner:2022.4
 
      - name: Run Aqua Security Scanner
        run: |
          docker run --rm \
            -v /tmp:/tmp \
            -v /var/run/docker.sock:/var/run/docker.sock \
            registry.aquasec.com/scanner:2022.4 scan \
            --registry "Docker Hub" \
            nginx:latest \
            --host http://ec2-54-183-33-60.us-west-1.compute.amazonaws.com:8080/ \
            --user ${{ secrets.AQUA_USER }} \
            --password ${{ secrets.AQUA_PASSWORD }} \
            --show-negligible \
            --htmlfile /tmp/out.html \
            --jsonfile /tmp/out.json > /dev/null
 
      - name: Copy Scan Artifacts
        run: |
          cp /tmp/out.html /tmp/out.json .
 
      - name: Upload Scan Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: |
            out.json
            out.html
